/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negocio;

/**
 *
 * @author Lisbeth
 */
public abstract class Stilo {

    public static String stilo
            = "<!DOCTYPE html>\n"
            + "<html>\n"
            + "<head lang=\"en\">\n"
            + "    <meta charset=\"UTF-8\">\n"
            + "    <style>\n"
            + "        .bs-callout {\n"
            + "            padding: 20px;\n"
            + "            margin: 20px 0;\n"
            + "            border: 1px solid #eee;\n"
            + "            border-left-width: 5px;\n"
            + "            border-radius: 3px;\n"
            + "        }\n"
            + "        .bs-callout h4 {\n"
            + "            margin-top: 0;\n"
            + "            margin-bottom: 5px;\n"
            + "        }\n"
            + "        .bs-callout p:last-child {\n"
            + "            margin-bottom: 0;\n"
            + "        }\n"
            + "        .bs-callout code {\n"
            + "            border-radius: 3px;\n"
            + "        }\n"
            + "        .bs-callout+.bs-callout {\n"
            + "            margin-top: -5px;\n"
            + "        }\n"
            + "        .bs-callout-default h4 {\n"
            + "            color: #777;\n"
            + "        }\n"
            + "        .bs-callout-primary {\n"
            + "            border-left-color: #428bca;\n"
            + "        }\n"
            + "        .bs-callout-primary h4 {\n"
            + "            color: #428bca;\n"
            + "        }\n"
            + "        .bs-callout-info {\n"
            + "            border-left-color: #5bc0de;\n"
            + "        }\n"
            + "        .bs-callout-info h4 {\n"
            + "            color: #5bc0de;\n"
            + "        }\n"
            + "        .bs-callout-default {\n"
            + "            border-left-color: #777;\n"
            + "        }\n"
            + "        .bs-callout-default h4 {\n"
            + "            color: #777;\n"
            + "        }\n"
            + "        .bs-callout-success {\n"
            + "            border-left-color: #5cb85c;\n"
            + "        }\n"
            + "        .bs-callout-success h4 {\n"
            + "            color: #5cb85c;\n"
            + "        }\n"
            + "        .bs-callout-danger {\n"
            + "            border-left-color: #d9534f;\n"
            + "        }\n"
            + "        .bs-callout-danger h4 {\n"
            + "            color: #d9534f;\n"
            + "        }\n"
            + "        .bs-callout-warning {\n"
            + "            border-left-color: #f0ad4e;\n"
            + "        }\n"
            + "        .bs-callout-warning h4 {\n"
            + "            color: #f0ad4e;\n"
            + "        }\n"
            + "        .bs-callout-info h4 {\n"
            + "            color: #5bc0de;\n"
            + "        }\n"
            + "        .container {\n"
            + "            padding-right: 15px;\n"
            + "            padding-left: 15px;\n"
            + "            margin-right: auto;\n"
            + "            margin-left: auto;\n"
            + "        }\n"
            + "        .container:before,\n"
            + "        .container:after {\n"
            + "            display: table;\n"
            + "            content: \" \";\n"
            + "        }\n"
            + "        .container:after {\n"
            + "            clear: both;\n"
            + "        }\n"
            + "        .container:before,\n"
            + "        .container:after {\n"
            + "            display: table;\n"
            + "            content: \" \";\n"
            + "        }\n"
            + "        .container:after {\n"
            + "            clear: both;\n"
            + "        }\n"
            + "        @media (min-width: 768px) {\n"
            + "            .container {\n"
            + "                width: 750px;\n"
            + "            }\n"
            + "        }\n"
            + "        @media (min-width: 992px) {\n"
            + "            .container {\n"
            + "                width: 970px;\n"
            + "            }\n"
            + "        }\n"
            + "        @media (min-width: 1200px) {\n"
            + "            .container {\n"
            + "                width: 1170px;\n"
            + "            }\n"
            + "        }\n"
            + "        .panel {\n"
            + "            margin-bottom: 20px;\n"
            + "            background-color: #ffffff;\n"
            + "            border: 1px solid transparent;\n"
            + "            border-radius: 4px;\n"
            + "            -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);\n"
            + "            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);\n"
            + "        }\n"
            + "        .panel-heading {\n"
            + "            padding: 10px 15px;\n"
            + "            border-bottom: 1px solid transparent;\n"
            + "            border-top-right-radius: 3px;\n"
            + "            border-top-left-radius: 3px;\n"
            + "        }\n"
            + "        .panel-title > a {\n"
            + "            color: inherit;\n"
            + "        }\n"
            + "        .panel-group .panel {\n"
            + "            margin-bottom: 0;\n"
            + "            overflow: hidden;\n"
            + "            border-radius: 4px;\n"
            + "        }\n"
            + "        .panel-group .panel + .panel {\n"
            + "            margin-top: 5px;\n"
            + "        }\n"
            + "        .panel-group .panel-heading {\n"
            + "            border-bottom: 0;\n"
            + "        }\n"
            + "        .panel-default > .panel-heading {\n"
            + "            color: #333333;\n"
            + "            background-color: #f5f5f5;\n"
            + "            border-color: #dddddd;\n"
            + "        }\n"
            + "        .panel-primary {\n"
            + "            border-color: #428bca;\n"
            + "        }\n"
            + "        .panel-primary > .panel-heading {\n"
            + "            color: #ffffff;\n"
            + "            background-color: #428bca;\n"
            + "            border-color: #428bca;\n"
            + "        }\n"
            + "table {    font-family: \"Lucida Sans Unicode\", \"Lucida Grande\", Sans-Serif;\n"
            + "           font-size: 12px;    margin:20px;  text-align: left;    border-collapse: collapse; }\n"
            + "\n"
            + "th {       font-size: 13px;     font-weight: normal;     padding: 8px;     background: #b9c9fe;\n"
            + "           border-top: 4px solid #aabcfe;    border-bottom: 1px solid #fff; color: #039; }\n"
            + "\n"
            + "td {       padding: 8px;     background: #e8edff;     border-bottom: 1px solid #fff;\n"
            + "           color: #669;    border-top: 1px solid transparent; }\n"
            + "\n"
            + "tr:hover td { background: #d0dafd; color: #339; }"
            + "\n"
            + "    </style>\n"
            + "    <title>Tecnologia Web</title>\n"
            + "</head>";
}
